### ISSUE TITLE
R console crashing (exercise 20) - fix

### ISSUE THREAD

**Issue by shoninouye** [kirstyflower/2019BMB-STAT5#1]
Hi @kirstyflower,

I was informed that you had some problems with error messages in exercise 20 of this course:

![](https://user-images.githubusercontent.com/40219472/50633154-e0007b00-0f7c-11e9-9c43-0f580df83408.png)
![](https://user-images.githubusercontent.com/40219472/50633155-e0007b00-0f7c-11e9-91c6-57f91ff410fa.png)
> User first comment: " In section 20, "ANOVA" of this course, between steps 4 and 5, the R console crashes and gives the error:
> 
> Oops, something went wrong.
If the problem persists, please report an issue.
> 
> refreshing does not fix this. I am not sure what I have done wrong, perhaps something in the SCT on the previous question?

&nbsp;

Exercise 20 (ANOVA) is a sequential exercise, and variables are not saved in-between steps of sequential exercises. So in step 5, we try to call `TukeyHSD(ANOVA1)` when `ANOVA1` is not available for that step. 

To solve this, the code to create `ANOVA1` can be added to the Pre-Exercise Code for this exercise _**OR**_ be added to the sample/solution code in this step:
```
# Perform ANOVA using the function aov(data~category) 
ANOVA1 <- aov(walk$speed~walk$treatment)

# Run a Tukey test using TukeyHSD()
TukeyHSD(ANOVA1)
```

&nbsp;

Also, I noticed from the build log that chapter 1 exercise 9 uses `check_arg(., "x")` in the SCT section when it _should_ most likely be `check_arg(., "formula")`:
![datacamp_-_course_overview](https://user-images.githubusercontent.com/22865592/51271549-d8d26780-1995-11e9-8a04-e992a83bad25.png)

**Comment by kirstyflower** [comment]
Hi! Thank you so much! My apologies for such a basic mistake. Thanks for your help. Kirsty

**Comment by shoninouye** [comment]
No need to apologize! You're welcome!
